<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/440px-NumPy_logo.svg.png"/>

# Numpy Exercise

In [84]:


labels_line = ['Age', 'Education', 'Income', 'HomeVal', 'Wealth', 'Balance']
banking = [
    ['35.9', '14.8', '91033', '183104', '220741', '38517'],
 ['37.7', '13.8', '86748', '163843', '223152', '40618'],
 ['36.8', '13.8', '72245', '142732', '176926', '35206'],
 ['35.3', '13.2', '70639', '145024', '166260', '33434'],
 ['35.3', '13.2', '64879', '135951', '148868', '28162'],
 ['34.8', '137', '75591', '155334', '188310', '36708'],
 ['39.3', '14.4', '80615', '181265', '201743', '38766'],
 ['36.6', '13.9', '76507', '149880', '189727', '34811'],
 ['35.7', '16.1', '107935', '276139', '211085', '41032'],
 ['40.5', '15.1', '82557', '182088', '220782', '41742'],
 ['37.9', '14.2', '58294', '123500', '132432', '29950'],
 ['43.1', '15.8', '88041', '194369', '267556', '51107'],
 ['37.7', '12.9', '64597', '119305', '186156', '34936'],
 ['36', '13.1', '64894', '141011', '160017', '32387'],
 ['40.4', '16.1', '61091', '194928', '113559', '32150'],
 ['33.8', '13.6', '76771', '159531', '197264', '37996'],
 ['36.4', '13.5', '55609', '123085', '105582', '24672'],
 ['37.7', '12.8', '74091', '143750', '217869', '37603'],
 ['36.2', '12.9', '', '112649', '117441', '26785'],
 ['39.1', '12.7', '60262', '126928', '161322', '32576'],
 ['39.4', '16.1', '111548', '230893', '331009', '56569'],
 ['36.1', '12.8', '48600', '105737', '106671', '26144'],
 ['35.3', '12.7', '51419', '104149', '111168', '24558'],
 ['37.5', '12.8', '51182', '106898', '88370', '23584'],
 ['34.4', '12.8', '60753', '95869', '', '26773'],
 ['33.7', '13.8', '64601', '103737', '134223', '27877'],
 ['40.4', '13.2', '62164', '114257', '144038', '28507'],
 ['38.9', '12.7', '46607', '94576', '114799', '27096'],
 ['34.3', '12.7', '61446', '122619', '161538', '28018'],
 ['38.7', '12.8', '62024', '134430', '149351', '31283'],
 ['33.4', '126', '54986', '105647', '126929', '24671'],
 ['35', '12.7', '48182', '114436', '102732', '25280'],
 ['38.1', '12.7', '47388', '92820', '118016', '24890'],
 ['34.9', '12.5', '55273', '102468', '126959', '26114'],
 ['36.1', '12.9', '53892', '92968', '129176', '27570'],
 ['32.7', '12.6', '47923', '104539', '88384', '20826'],
 ['37.1', '12.5', '46176', '92654', '101964', '23858'],
 ['23.5', '13.6', '33088', '105430', '44223', '20834'],
 ['38', '13.6', '53890', '108446', '95013', '26542'],
 ['33.6', '12.7', '57390', '111836', '134434', '27396'],
 ['41.7', '13', '48439', '100788', '124474', '31054'],
 ['36.6', '14.1', '56803', '149138', '101695', '29198'],
 ['34.9', '12.4', '52392', '93875', '133101', '24650'],
 ['36.7', '12.8', '48631', '95490', '105202', '23610'],
 ['38.4', '12.5', '52500', '105377', '139199', '29706'],
 ['34.8', '12.5', '42401', '106478', '94867', '21572'],
 ['33.6', '12.7', '64792', '116071', '185714', '32677'],
 ['37', '14.1', '59842', '106949', '135329', '29347'],
 ['34.4', '12.7', '65625', '129688', '175000', '29127'],
 ['37.2', '12.5', '54044', '108654', '140726', '27753'],
 ['35.7', '12.6', '39707', '89552', '80124', '21345'],
 ['37.8', '12.9', '45286', '108431', '91928', '28174'],
 ['35.6', '12.8', '37784', '92712', '60721', '19125'],
 ['35.7', '12.4', '52284', '92143', '146028', '29763'],
 ['34.3', '12.4', '42944', '86192', '98778', '22275'],
 ['39.8', '13.4', '46036', '99508', '98343', '27005'],
 ['36.2', '12.3', '50357', '90750', '126613', '24076'],
 ['35.1', '12.3', '45521', '82720', '105346', '23293'],
 ['35.6', '16.1', '30418', '139739', '24999', '16854'],
 ['40.7', '12.7', '52500', '94792', '147222', '28867'],
 ['33.5', '12.5', '41795', '94456', '91806', '21556'],
 ['37.5', '12.5', '66667', '78906', '143750', '31758'],
 ['37.6', '12.9', '38596', '95364', '54453', '17939'],
 ['39.1', '12.6', '44286', '93103', '110465', '22579'],
 ['33.1', '12.2', '37287', '75561', '', '19343'],
 ['36.4', '12.9', '38184', '80099', '76438', '21534'],
 ['37.3', '12.5', '47119', '88958', '102993', '22357'],
 ['38.7', '13.6', '44520', '96112', '93915', '25276'],
 ['36.9', '12.7', '52838', '101705', '75040', '23077'],
 ['32.7', '12.3', '34688', '82870', '93750', '20082'],
 ['36.1', '12.4', '31770', '74525', '47446', '15912'],
 ['39.5', '12.8', '32994', '89223', '50592', '21145'],
 ['36.5', '12.3', '33891', '72739', '81880', '18340'],
 ['32.9', '12.4', '37813', '86667', '69643', '19196'],
 ['29.9', '12.3', '46528', '88889', '96591', '21798'],
 ['32.1', '12.3', '30319', '67083', '34367', '13677'],
 ['36.1', '13.3', '36492', '172768', '24999', '20572'],
 ['35.9', '12.4', '51818', '80357', '135185', '26242'],
 ['32.7', '12.2', '35625', '64737', '76321', '17077'],
 ['37.2', '12.6', '36789', '86563', '69764', '20020'],
 ['38.8', '12.3', '42750', '77717', '95192', '25385'],
 ['37.5', '13', '30412', '138911', '24999', '20463'],
 ['36.4', '12.5', '37083', '70909', '95833', '21670'],
 ['42.4', '12.6', '31563', '81597', '71759', '15961'],
 ['19.5', '16.1', '15395', '67500', '24999', '5956'],
 ['30.5', '12.8', '21433', '83456', '24999', '11380'],
 ['33.2', '12.3', '31250', '91049', '52976', '18959'],
 ['36.7', '12.5', '31344', '77541', '36510', '16100'],
 ['32.4', '12.6', '29733', '60252', '27531', '14620'],
 ['36.5', '12.4', '41607', '76270', '98455', '22340'],
 ['33.9', '12.1', '32813', '40313', '79167', '26405'],
 ['29.6', '12.1', '', '52096', '24999', '13693'],
 ['37.5', '11.1', '34896', '65357', '81818', '20586'],
 ['34', '12.6', '20578', '113239', '24999', '14095'],
 ['28.7', '12.1', '32574', '50244', '49662', '14393'],
 ['36.1', '12.2', '30589', '69375', '48890', '16352'],
 ['30.6', '12.3', '26565', '64038', '42543', '17410'],
 ['22.8', '12.3', '16590', '67850', '24999', '10436'],
 ['30.3', '12.2', '9354', '91708', '24999', '9904'],
 ['22', '12', '14115', '53923', '24999', '9071'],
 ['30.8', '11.9', '17992', '46885', '24999', '10679'],
 ['35.1', '11', '7741', '99375', '24999', '6207']]

In [85]:
bank = np.array(banking, float)
print bank

ValueError: could not convert string to float:

In [ ]:
# We didn't clean our input! lest filter out  
bank = np.array([row for row in banking if not '' in row], float)

# Lets start exploring
print "Dimensions:", bank.shape, "\n"

In [ ]:
# So we have 6 columns and 98 rows. 
# Lets transpose the array and add the column names. 

Age, Education, Income, HomeVal, Wealth, Balance = np.transpose(bank)
bank_columns = [Age, Education, Income, HomeVal, Wealth, Balance]
print Age

__Whats the average age of a bank customers?__

In [86]:
print "Mean Age: ", Age.mean()
print "Std: ", Age.std()

Mean Age:  35.538775510204076
Std:  3.8905860387754614

__What's the rate of customers over 40 y/o with an overdraft?__

In [87]:
# lets get rid of that 1.500e+00 format
np.set_printoptions(suppress=True)

# now filter those under 40
where_condition = bank[:, 0] >= 40
over_40 = bank[where_condition]
print over_40, '\n'

print "Balance:" , over_40[5].mean()

[[    40.5     15.1  82557.  182088.  220782.   41742. ]
 [    43.1     15.8  88041.  194369.  267556.   51107. ]
 [    40.4     16.1  61091.  194928.  113559.   32150. ]
 [    40.4     13.2  62164.  114257.  144038.   28507. ]
 [    41.7     13.   48439.  100788.  124474.   31054. ]
 [    40.7     12.7  52500.   94792.  147222.   28867. ]
 [    42.4     12.6  31563.   81597.   71759.   15961. ]]

Balance: 53905.73333333334

__mm... Do older people have a higher balance?__

In [88]:
print "Balance:" , bank[:, 5].mean()
print "Balance over 40:" , over_40[5].mean()

Balance: 25020.102040816328
Balance over 40: 53905.73333333334

__mm... ok, but does age correlates with balance?__

In [89]:
age = bank[:, 0]
balance = bank[:, 5]
np.corrcoef(age, balance)

array([[1. , 0.6],
       [0.6, 1. ]])



__mm... ok, are any of the other variables correlated?__

In [91]:
corr_matrix = np.corrcoef(bank.T)
print(corr_matrix)

[[ 1.  -0.   0.5  0.4  0.5  0.6]
 [-0.   1.   0.2  0.1  0.1  0.1]
 [ 0.5  0.2  1.   0.8  0.9  1. ]
 [ 0.4  0.1  0.8  1.   0.7  0.8]
 [ 0.5  0.1  0.9  0.7  1.   0.9]
 [ 0.6  0.1  1.   0.8  0.9  1. ]]